branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: api.ddad-bd.com
  branch: master
  default_ec2_keyname: aws-eb
  default_platform: PHP 7.4 running on 64bit Amazon Linux 2
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: ddad-bd
  sc: git
  workspace_type: Application
